### ISSUE TITLE
Неправильный результат алгоритма Джарвиса

### ISSUE THREAD

**Issue by MihailPohodeev** [MihailPohodeev/Minimal-Convex-Hull_RUBY-GEM#1]
![Screenshot from 2024-06-02 16-20-28](https://github.com/MihailPohodeev/Minimal-Convex-Hull_RUBY-GEM/assets/115114201/f0db30e7-77ce-44dc-a23d-ea006a3aeb38)
![Screenshot from 2024-06-02 16-22-15](https://github.com/MihailPohodeev/Minimal-Convex-Hull_RUBY-GEM/assets/115114201/b162d522-dcc7-47fc-986d-a9aa02508da0)
Очевидно, неверный результат

**Comment by pedevyat** [comment]
Проблема устранена. 5660184a674f92b17030181139105f6a3bc898e2

**Comment by MihailPohodeev** [comment]
отлично
