### ISSUE TITLE
Неверное поведение функции Грэхема при передаче одной точке

### ISSUE THREAD

**Issue by pedevyat** [MihailPohodeev/Minimal-Convex-Hull_RUBY-GEM#2]
![image](https://github.com/MihailPohodeev/Minimal-Convex-Hull_RUBY-GEM/assets/114941602/98ddba59-9e83-4c20-851e-4018581bbb34)
![image](https://github.com/MihailPohodeev/Minimal-Convex-Hull_RUBY-GEM/assets/114941602/32138111-c31a-4fe0-9481-27d02effe26a)

**Comment by MihailPohodeev** [comment]
Исправлено 05a9f43
