### ISSUE TITLE
Некорректное поведение функции Джарвиса на пустом массиве

### ISSUE THREAD

**Issue by MihailPohodeev** [MihailPohodeev/Minimal-Convex-Hull_RUBY-GEM#3]
![Screenshot from 2024-06-02 17-51-11](https://github.com/MihailPohodeev/Minimal-Convex-Hull_RUBY-GEM/assets/115114201/b8a3b4f4-5b8d-47c6-bf71-14426d12b8eb)
![Screenshot from 2024-06-02 17-50-45](https://github.com/MihailPohodeev/Minimal-Convex-Hull_RUBY-GEM/assets/115114201/5829ff38-70e9-44ac-be8b-5e7cf37cff76)
Возникновение ошибки!

**Comment by pedevyat** [comment]
Исправлено. aad0608c7173e9cab9823274a9f840455b1505e0
